#!/bin/sh

config="${XDG_CONFIG_HOME:-"$HOME/.config"}/nota"

# shellcheck disable=SC1090
[ -f "$config" ] && . "$config"

data_base_dir=${XDG_DATA_HOME:-"$HOME/.local/share"}
data_dir=$data_base_dir/nota

mkdir -p "$data_dir"
cd -- "$data_dir" || exit

editor=${EDITOR:-${VISUAL:-vi}}
unsanitised_basename=${1:-"$(date +%F)"}

export GIT_DIR="$data_dir/.git"
export GIT_WORK_TREE="$data_dir"

case $unsanitised_basename in
    git|ls) exec "$@" ;;
    *' days ago'|yesterday|tomorrow)
        unsanitised_basename=$(date -d "$unsanitised_basename" +%F)
    ;;
    todo)
        unsanitised_basename=todo/$(date +%F)
    ;;
esac

# Can't use ${file//...} because it's undefined in POSIX sh
basename=$(printf '%s' "$unsanitised_basename" | tr / _)
file=$data_dir/$basename
[ "$GPG" ] && file=$file.gpg

"$editor" -- "$file"

# It's possible we exited the editor without creating a file in the new case
if ! [ -f "$file" ]; then
    printf 'Not committing as %s is missing\n' "$unsanitised_basename" >&2
    exit 5
fi

git init
git add "$file"
git commit -m "Updated $unsanitised_basename"
